name: Main Test
on: [pull_request]

jobs:
  validate_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: ✔ HTML5 Validator
        uses: NTIG-Uppsala/html5validator-action@master
        with:
          root: /
          css: true

  run_tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - run: pip install selenium
      - run: python test.py
