name: Main Test
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install selenium
      - run: python test.py


    