on: 
  pull_request:
    branches: 
      - main
jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: python -m http.server
      - run: pip install selenium
      - run: python -m unittest discover -s tests
