on: 
  pull_request:
    branches: 
      - main
jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install selenium
      - run: python -m http.server 8000 &  sleep 5  
      - run: python -m unittest discover -s tests
      - run: SERVER_PID=$(cat server_pid) kill $SERVER_PID
