on: 
  pull_request:
    branches: 
      - main
jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install selenium
      - run: Start-Process -NoNewWindow python -ArgumentList "-m", "http.server", "8000"  
      - run: Start-Sleep -Seconds 20
      - run: python -m unittest discover -s tests
      - run: Stop-Process -Name "python" -Force -ErrorAction SilentlyContinue

