on: 
  pull_request:
    branches: 
      - main
jobs:
  run-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install selenium
      - run: python -m http.server 8000 
      - run: $env:SERVER_PID = $LASTEXITCODE
      - run: Start-Sleep -Seconds 5  
      - run: python -m unittest discover -s tests
      - run: Stop-Process -Id $env:SERVER_PID
          
